Add secrets capability
chasinglogic/ansible-role-podman pull request #8
Opened 2023-12-15 17:31 UTC by oddomatik

This is a feature we've incorporated for our use internally. Allows mount of secrets into podman containers.

2023-12-15 18:37 UTC, chasinglogic requested changes
Thanks for the contribution, just some minor stuff to make the example more copy pastable then I will get this merged.

2023-12-15 18:37 UTC, chasinglogic commented on README.md
> +        uid: [0]
can we just set these to the defaults?

2023-12-15 18:37 UTC, chasinglogic commented on README.md
> +        type: [mount (default)|env]
I'd prefer if we used comments for documentation and that the values are valid values in the example as much as possible.

2023-12-15 18:37 UTC, chasinglogic commented on README.md
> +    # values have defaults as specified in podman documentation
just slap this link on the end of the comment please: https://docs.podman.io/en/v4.6.0/markdown/options/secret.html

2023-12-15 20:44 UTC, oddomatik commented on README.md
> +        type: [mount (default)|env]
I believe I've understood but feel free to elaborate!

2023-12-18 08:54 UTC, chasinglogic commented
Perfect, thanks again!

2023-12-18 08:54 UTC, chasinglogic approved these changes

2023-12-18 08:54 UTC, merged

2023-12-18 09:08 UTC, chasinglogic commented
This has now been released in version 1.3.0